apiVersion: v1
data:
 Corefile: |
   .:53 {
       errors
       ready
       health
       kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
       }
       prometheus :9153
       forward . /etc/resolv.conf
       cache 10
       loop
       reload
       loadbalance
   }
   europe-west4.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 34.90.226.166 {      # <---- Modify
       }
   }
   uksouth.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 20.108.98.41 {      # <---- Modify
       }
   }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system