apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
data:
  commands.txt: |
    connect http://bank-server:8090/api
    set-thread-pool-size --size 300
    set-pool-size --size 500
    transfer --concurrency 20 --limit 1000
    balance --followerReads --concurrency 5 --limit 1000