apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  cockroach.server: | # you may select any name here, but it must end with the .server file extension
    eu-west-1.svc.cluster.local:53 {
        errors
        cache 30
        forward . 52.211.227.198 99.80.3.29 99.81.126.100 {
          force_tcp
        }
    }
    europe-west4.svc.cluster.local:53 {
        errors
        cache 30
        forward . 35.234.175.241
    }