apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  cockroach.server: | # you may select any name here, but it must end with the .server file extension
    eu-west-1.svc.cluster.local:53 {
        errors
        cache 30
        forward . 54.75.28.214 63.35.58.105 54.74.115.114  {
          force_tcp
        }
    }
    europe-west4.svc.cluster.local:53 {
        errors
        cache 30
        forward . 34.32.196.125
    }