apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: coredns
  namespace: kube-system
data:
 Corefile: |
   .:53 {
       errors
       ready
       health
       kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
       }
       prometheus :9153
       forward . /etc/resolv.conf
       cache 10
       loop
       reload
       loadbalance
   }
   eu-west-1.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 52.211.227.198 99.80.3.29 99.81.126.100 {      # <---- Modify
            force_tcp            # <---- Modify
       }
   }
   uksouth.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 20.108.212.112 {      # <---- Modify
       }
   }